window.WORDS_AGLOW_LEVELS = [
  {
    id: 'level-1',
    number: 1,
    name: 'Learn the Wind',
    title: '第一關：讓燈乘風',
    intent: '教會 Space 放燈與 A / D 基本修正。答案明顯、速度慢、容錯大。',
    hint: '先把「先」送到「一、馬、當」附近。這關不用急，先感受風的慣性。',
    idioms: ['一馬當先'],
    queue: ['先', '山', '水', '月', '星', '雲', '火'],
    layout: [
      { x: 170, y: 72, character: '燈', anchor: true },
      { x: 222, y: 72, character: '火', anchor: true },
      { x: 274, y: 72, character: '夜', anchor: true },
      { x: 170, y: 123, character: '一' },
      { x: 216, y: 151, character: '馬' },
      { x: 262, y: 123, character: '當' },
    ],
    physics: {
      riseSpeed: 0.86,
      midRiseSpeed: 0.66,
      nearRiseSpeed: 0.48,
      midSlowdownDistance: 155,
      nearSlowdownDistance: 105,
      riseResponse: 0.045,
      windAcceleration: 0.050,
      windRampUp: 0.043,
      windRampDown: 0.064,
      horizontalDrag: 0.990,
      maxHorizontalSpeed: 2.15,
      maxWind: 0.55,
    },
    rules: {
      maxShots: 4,
      targetClears: 1,
      failY: 535,
    },
    launch: { defaultX: 230 },
  },
  {
    id: 'level-2',
    number: 2,
    name: 'Learn Counter-Steering',
    title: '第二關：提早反吹',
    intent: '只有一個明顯答案，但燈群偏左、速度更快。重點是先加速，再用反向風煞車。',
    hint: '「足」要去左側的「畫、蛇、添」。試著先按 A 拉過去，快到時提早按 D 煞住。',
    idioms: ['畫蛇添足'],
    queue: ['足', '月', '山', '水', '星', '雲', '火', '地'],
    layout: [
      { x: 76, y: 72, character: '燈', anchor: true },
      { x: 128, y: 72, character: '火', anchor: true },
      { x: 180, y: 72, character: '夜', anchor: true },
      { x: 90, y: 123, character: '畫' },
      { x: 136, y: 151, character: '蛇' },
      { x: 182, y: 123, character: '添' },
      { x: 260, y: 72, character: '月', anchor: true },
      { x: 312, y: 72, character: '星', anchor: true },
    ],
    physics: {
      riseSpeed: 1.08,
      midRiseSpeed: 0.82,
      nearRiseSpeed: 0.58,
      midSlowdownDistance: 150,
      nearSlowdownDistance: 100,
      riseResponse: 0.048,
      windAcceleration: 0.054,
      windRampUp: 0.046,
      windRampDown: 0.062,
      horizontalDrag: 0.990,
      maxHorizontalSpeed: 2.35,
      maxWind: 0.58,
    },
    rules: {
      maxShots: 5,
      targetClears: 1,
      failY: 535,
    },
    launch: { defaultX: 330 },
  },
  {
    id: 'level-3',
    number: 3,
    name: 'First Real Decision',
    title: '第三關：一個「心」，兩條路',
    intent: '第一次同時存在兩條可完成路線。操作不特別刁鑽，真正的難點是看 preview、決定先完成哪一邊，還要替中間的干擾字找位置。',
    hint: '第一顆「心」左右兩邊都能完成成語。注意下一顆是「山」、再下一顆又是「心」。先想好三步。',
    idioms: ['心花怒放', '心平氣和'],
    queue: ['心', '山', '心', '月', '水', '火', '雲', '星', '地', '夜'],
    layout: [
      { x: 70, y: 72, character: '燈', anchor: true },
      { x: 122, y: 72, character: '火', anchor: true },
      { x: 174, y: 72, character: '夜', anchor: true },
      { x: 286, y: 72, character: '月', anchor: true },
      { x: 338, y: 72, character: '星', anchor: true },
      { x: 390, y: 72, character: '雲', anchor: true },
      { x: 92, y: 123, character: '花' },
      { x: 138, y: 151, character: '怒' },
      { x: 184, y: 123, character: '放' },
      { x: 276, y: 123, character: '平' },
      { x: 322, y: 151, character: '氣' },
      { x: 368, y: 123, character: '和' },
    ],
    physics: {
      riseSpeed: 0.98,
      midRiseSpeed: 0.76,
      nearRiseSpeed: 0.55,
      midSlowdownDistance: 155,
      nearSlowdownDistance: 105,
      riseResponse: 0.046,
      windAcceleration: 0.052,
      windRampUp: 0.045,
      windRampDown: 0.064,
      horizontalDrag: 0.990,
      maxHorizontalSpeed: 2.25,
      maxWind: 0.56,
    },
    rules: {
      maxShots: 6,
      targetClears: 2,
      failY: 535,
    },
    launch: { defaultX: 230 },
  },
];
